name: train-model

on:
  push:
    branches-ignore:
      - master

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python model/model.py

          echo "## Model metrics" > report.md
          cat model/metrics.txt >> report.md

          cml-send-comment report.md
          