name: push-model
on: 
  push:
    branches:
      - master
jobs:
  model-push:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Get model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          pip install -r requirements.txt
          dvc repro
      - name: Commit report
        run: |
          git config --global user.name 'IlyaCES'
          git config --global user.email 'IlyaCES@users.noreply.github.com'
          git add models/m.model
          git commit -m "Model added"
          git push